export const icons: { [key: string]: string } = {
    email: '/assets/mail.svg',
    user: '/assets/user.svg',
    arrowLeft: '/assets/arrow_left.svg',
    lock: '/assets/lock.svg',
    home: '/assets/home.svg',
    menu: '/assets/Menu.svg',
    homeAlt: '/assets/homeAlt.svg',
    search: '/assets/searchIcon.svg',
    notification: '/assets/notifyIcon.svg',
    profileImg: '/assets/profileImg.png',
    AddIcon: '/assets/cruzBotones.svg',
    Dashboard: '/assets/dashboardIcon.svg',
    Proyectos: 'assets/proyectsIcon.svg',
    Equipo: 'assets/teamIcon.svg',
    Finanzas: 'assets/financeIcon.svg',
    Contactos: 'assets/contactsIcon.svg',
    Configuracion: 'assets/settingsIcon.svg',
    SideBar: 'assets/sidebar.svg',
    sidebarIcon: 'assets/sidebarIcon.svg',
    whiteboardIcon: 'assets/whiteboardIcon.svg',
    calendarIcon: 'assets/calendarIcon.svg',
    notificationIcon: 'assets/notificationIcon.svg',
};