import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/providers/NextAuth";
import { AuthContextProvider } from "@/context/AuthContext";
import { AppContextProvider } from "@/context/AppContext";
import SnackbarCustom from "@/components/UI/Alerts";
import LoadingScreen from "@/components/UI/LoadingScreen";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NextAuthProvider>
      <AppContextProvider>
        <AuthContextProvider>
          <html lang="en">
            <body>
              <LoadingScreen />
              <SnackbarCustom />
              {children}
            </body>
          </html>
        </AuthContextProvider>
      </AppContextProvider>

    </NextAuthProvider>
  );
}
