import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/providers/NextAuth";
import { AuthContextProvider } from "@/context/AuthContext";
import { AppContextProvider } from "@/context/AppContext";
import SnackbarCustom from "@/components/UI/Alerts";
import LoadingScreen from "@/components/UI/LoadingScreen";
import { CompanyContext, CompanyContextProvider } from "@/context/CompanyContext";

export const metadata: Metadata = {
  title: "Workit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NextAuthProvider>
      <AppContextProvider>

        <AuthContextProvider>
          <CompanyContextProvider>

            <html lang="en">
              <body>
                <LoadingScreen />
                <SnackbarCustom />
                {children}
              </body>
            </html>


          </CompanyContextProvider>
        </AuthContextProvider>
      </AppContextProvider>
    </NextAuthProvider>
  );
}
